//
// This Resource File will Swap in new strings intended in general to remove any Appian specific strings
// and replace them with more Generic strings
//
#ifdef GENERIC_TEXT


#ifdef IDS_MONITOR_ORDER_ALERT
#undef IDS_MONITOR_ORDER_ALERT
#define IDS_MONITOR_ORDER_ALERT	IDS_GENERIC_MONITOR_ORDER_ALERT
#endif //IDS_MONITOR_ORDER_ALERT
#ifdef IDS_POPUP_MENU
#undef IDS_POPUP_MENU
#define IDS_POPUP_MENU	IDS_GENERIC_POPUP_MENU
#endif //IDS_POPUP_MENU
#ifdef IDS_APPIANMAX
#undef IDS_APPIANMAX
#define IDS_APPIANMAX	IDS_GENERIC_APPIANMAX
#endif //IDS_APPIANMAX
#ifdef IDS_WRONG_SHELL
#undef IDS_WRONG_SHELL
#define IDS_WRONG_SHELL	IDS_GENERIC_WRONG_SHELL
#endif //IDS_WRONG_SHELL
#ifdef IDS_ALREADY_RUNNING
#undef IDS_ALREADY_RUNNING
#define IDS_ALREADY_RUNNING	IDS_GENERIC_ALREADY_RUNNING
#endif //IDS_ALREADY_RUNNING
#ifdef AFX_IDS_APP_TITLE
#undef AFX_IDS_APP_TITLE
#define AFX_IDS_APP_TITLE	AFX_IDS_GENERIC_APP_TITLE
#endif //AFX_IDS_APP_TITLE
#ifdef IDS_APPIAN_INDIV_TITLE
#undef IDS_APPIAN_INDIV_TITLE
#define IDS_APPIAN_INDIV_TITLE	IDS_GENERIC_APPIAN_INDIV_TITLE
#endif //IDS_APPIAN_INDIV_TITLE
#ifdef IDS_APP_NAME
#undef IDS_APP_NAME
#define IDS_APP_NAME	IDS_GENERIC_APP_NAME
#endif //IDS_APP_NAME



#endif //GENERIC_TEXT