#ifndef __INTERAPP_H__
#define __INTERAPP_H__

#define APPIANMESSAGESTRING	"WM_APPIAN_TASKBAR_HOOK"

#define APPIAN_PARAM_UPDATE_REGISTRY	0

#define APPIAN_PARAM_GETMINMAXINFO		1				

#define APPIAN_PARAM_CREATE				2

#define APPIAN_PARAM_RESTORE			3

#define APPIAN_PARAM_MAXIMIZE			4

#define APPIAN_PARAM_MINIMIZE			5

#define APPIAN_PARAM_CLOSE				6

#define APPIAN_PARAM_SHOWWINDOW			7

#define APPIAN_PARAM_EXITSIZEMOVE		8

#define APPIAN_PARAM_DESTROY			9

#define APPIAN_PARAM_WINDOWPOSCHANGING	10

#define APPIAN_PARAM_ACTIVATEAPP		11

#define APPIAN_PARAM_SIZE				12

#define APPIAN_PARAM_SETTEXT			13

#define APPIAN_PARAM_WINDOWPOSCHANGED	14

#define	APPIAN_PARAM_ACCESSIBILITYSTATE		15
#define	APPIAN_PARAM_ACTIVATESHELLWINDOW	16
#define	APPIAN_PARAM_APPCOMMAND				17
#define	APPIAN_PARAM_GETMINRECT				18
#define	APPIAN_PARAM_LANGUAGE				19
#define	APPIAN_PARAM_REDRAW					20
#define	APPIAN_PARAM_TASKMAN				21
#define	APPIAN_PARAM_WINDOWACTIVATED		22
#define	APPIAN_PARAM_WINDOWCREATED			23
#define	APPIAN_PARAM_WINDOWDESTROYED		24
#define	APPIAN_PARAM_WINDOWREPLACED			25
#define APPIAN_PARAM_ENTERSIZEMOVE			26
#define APPIAN_PARAM_ANYWINDOWPOSCHANGED	27

#endif
